title: Ofer Shachar # your name (or website title) here
logo: "/images/github_image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent Graduate of the Double Bachelor of Physics and Electrical Engineering at the Tel Aviv University.
  Teaching Assistant at the Digital Electronic Circuits Course at The Tel Aviv University and previously
  an Electronic Lab Instructor.
  Looking for my first hardware/software job.
  
  <br><br>
  <a href="https://www.linkedin.com/in/ofer-shachar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
